name: terraform-apply
'on':
  workflow_call:
    inputs:
      terraform-cli-version:
        required: false
        type: string
        default: 1.9.5
      working-dir:
        required: false
        type: string
        default: terraform
env:
  WORKING-DIR: '${{ inputs.working-dir }}'
jobs:
  oidc_debug_test:
    if: false
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v4
        with:
          repository: github/actions-oidc-debugger
          ref: main
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: '${{ github.server_url }}/${{ github.repository_owner }}'
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: '${{ env.WORKING-DIR }}'
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: 'arn:aws:iam::183631350996:role/IaC'
      - name: Get secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: >
            ,arn:aws:secretsmanager:us-east-1:183631350996:secret:github-actions/terraform-cloud-AJdvsd
          name-transformation: none
          parse-json-secrets: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '${{ inputs.terraform-cli-version }}'
      - id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - id: init
        run: terraform init
      - id: validate
        run: terraform validate -no-color
      - id: apply
        run: terraform apply -auto-approve
