name: terraform-plan
on:
    workflow_call:
        inputs:
            terraform-cli-version:
                required: false
                type: string
                default: "1.9.5"
            working-dir:
                required: false
                type: string
                default: "terraform"

env:
    WORKING-DIR: ${{ inputs.working-dir }}

jobs:
    plan:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ${{ env.WORKING-DIR }}
        steps:
            - uses: actions/checkout@v4
            - uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: ${{ inputs.terraform-cli-version }}
            - id: init
              run: terraform init
