name: terraform-plan
on:
    workflow_call:
        inputs:
            terraform-cli-version:
                required: false
                type: string
                default: "1.7.5"

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                ref: CLOUD-2-test-tf-plan-workflow
    list-directories:
        needs: checkout
        runs-on: ubuntu-latest
        steps:
            - run: |
                pwd
                ls
