name: terraform-plan
on:
    workflow_call:
        inputs:
            terraform-cli-version:
                required: false
                type: string
                default: "1.7.5"

jobs:
    list-directories:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                ls
