name: Terrgaunt Apply

on:
  workflow_call:
    inputs:
      tofu_version:
        description: "Tofu version"
        required: false
        type: string
        default: "1.8.1"
      tg_version:
        description: "Terragrunt version"
        required: false
        type: string
        default: "0.67.0"
      working_directory:
        description: "Working directory for terragrunt"
        required: true
        type: string
      role_to_assume:
        description: "Role to assume for Terragrunt Apply Workflow"
        required: true
        type: string
      enable_oidc_debugger:
        description: "Enable OIDC Debugger"
        required: false
        type: boolean
        default: false
      github_environment:
        description: "GitHub Environment"
        required: true
        type: string

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  oidc_debug_test:
    if: ${{ inputs.enable_oidc_debugger }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: OIDC Debugger
    steps:
      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: "${{ github.server_url }}/${{ github.repository_owner }}"

  apply:
    runs-on: ubuntu-latest
    container:
      image: "public.ecr.aws/z5i5o7e1/yashrajdighe/my-iac:latest"
    env:
      GITHUB_TOKEN: ${{ secrets.github_token }}
      TG_PROVIDER_CACHE: 1
      TG_PROVIDER_CACHE_DIR: "/tmp/.terragrunt-cache"
    environment: ${{ inputs.github_environment }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Create Cache Directory
        run: mkdir -p $TF_PLUGIN_CACHE_DIR

      - name: Configure AWS Credentials for Terragrunt Apply
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: us-east-1

      # Added init step to avoid race condition with cache directory creation
      - name: Init
        shell: bash
        working-directory: ${{ inputs.working_directory }}
        run: |
          terragrunt run-all init --terragrunt-parallelism 1

      - name: Apply
        shell: bash
        working-directory: ${{ inputs.working_directory }}
        run: terragrunt run-all apply --terragrunt-non-interactive
