name: Terrgaunt Plan

on:
  workflow_call:
    inputs:
      tofu_version:
        description: "Tofu version"
        required: false
        type: string
        default: "1.8.1"
      tg_version:
        description: "Terragrunt version"
        required: false
        type: string
        default: "0.67.0"
      working_directory:
        description: "Working directory for terragrunt"
        required: true
        type: string
      role_to_assume:
        description: "Role to assume for Terragrunt Plan Workflow"
        required: true
        type: string
      enable_oidc_debugger:
        description: "Enable OIDC Debugger"
        required: false
        type: boolean
        default: false

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  oidc_debug_test:
    if: ${{ inputs.enable_oidc_debugger }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: OIDC Debugger
    steps:
      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: "${{ github.server_url }}/${{ github.repository_owner }}"

  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ inputs.tofu_version }}
          tg_version: ${{ inputs.tg_version }}
          tg_dir: ${{ inputs.working_directory }}
          tg_command: "hclfmt --terragrunt-check --terragrunt-diff"

  plan:
    runs-on: ubuntu-latest
    container:
      image: "public.ecr.aws/z5i5o7e1/yashrajdighe/my-iac:latest"
    needs:
      - checks
    env:
      GITHUB_TOKEN: ${{ secrets.github_token }}
      TERRAGRUNT_NON_INTERACTIVE: true # for backward compatibility
      TG_NON_INTERACTIVE: true
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Create Cache Directory
        run: mkdir -p $TF_PLUGIN_CACHE_DIR

      - name: Configure AWS Credentials for Terragrunt Plan
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: us-east-1

      # Added init step to avoid race condition with cache directory creation
      - name: Init
        shell: bash
        working-directory: ${{ inputs.working_directory }}
        run: |
          terragrunt run-all init --terragrunt-parallelism 1

      - name: Plan
        shell: bash
        working-directory: ${{ inputs.working_directory }}
        run: |
          terragrunt run-all plan
