name: Terrgaunt Plan

on:
  workflow_call:
    inputs:
      tofu_version:
        description: 'Tofu version'
        required: false
        type: string
        default: '1.8.1'
      tg_version:
        description: 'Terragrunt version'
        required: false
        type: string
        default: '0.67.0'
      working_directory:
        description: 'Working directory for terragrunt'
        required: true
        type: string
      role-to-assume:
        description: 'Role to assume for Terragrunt'
        required: true
        type: string
      enable-oidc-debugger:
        description: 'Enable OIDC Debugger'
        required: false
        type: boolean
        default: false

jobs:
  oidc_debug_test:
    if: ${{ inputs.enable-oidc-debugger }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: OIDC Debugger
    steps:
      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: '${{ github.server_url }}/${{ github.repository_owner }}'

  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ inputs.tofu_version }}
          tg_version: ${{ inputs.tg_version }}
          tg_dir: ${{ inputs.working_directory }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
  
  aws-configure:
    runs-on: ubuntu-latest
    needs: [ checks ]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials for Terragrunt
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}

  plan:
    runs-on: ubuntu-latest
    needs: [ aws-configure ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ inputs.tofu_version }}
          tg_version: ${{ inputs.tg_version }}
          tg_dir: ${{ inputs.working_directory }}
          tg_command: 'plan'
